base_gpt-3.5-turbo:
  openai: true
  model: gpt-3.5-turbo
  max_tokens: 4096
  temperature: 1.0
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
local_llama_3_instruct_7b:
  openai: false
  model: lmstudio-community/Meta-Llama-3-8B-Instruct-GGUF
  max_tokens: -1
  temperature: 1.0
  url: http://localhost:1234/v1/
